### ISSUE TITLE
Server install

### ISSUE THREAD

**Issue by Chopper00** [gomfunkel/homebridge-wifi-environment-sensor#1]
Hi, great project, i am new to IOT, i have nodemcu running with your "bme280_nodemcu.ino", homebridge working on rpi, how do i enable the web service on rpi ?

**Comment by gomfunkel** [comment]
Hey @Chopper00,

having Node.js installed on the Pi, which you already should have as it's a required by Homebridge, you simply need to enter the `server` directory and then `npm install .`. All information necessary for the installation is in the `package.xml`.

After installation you simply start the server with `node server.js`. You probably want to think about running the server as a service or in a screen session after making sure it works to have it running permanently.

**Comment by max-behr** [comment]
Hi, very great project. I have all the prerequisites installed except sqlite3 because of the error: Error: Cannot find module '/home/pi/homebridge-wifi-environment-sensor/server/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/homebridge-wifi-environment-sensor/server/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
